### ISSUE TITLE
GHA fails for Python 2.7 and 3.5

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zope.paste#5]
It seems the current version of `paste.deploy` no longer supports Python < 3.6.

See https://github.com/zopefoundation/zope.paste/actions/runs/3307004634/jobs/5458310472

Proposed solution: Drop support for Python < 3.6 as `zope.paste` does not seem to be very widely used and we have to drop support for that ancient versions anyway in the future.

**Comment by hugovk** [comment]
Please see PR https://github.com/zopefoundation/zope.paste/pull/6, also drops EOL 3.6 and adds new 3.10 and 3.11.
